### ISSUE TITLE
Settings Not Saving

### ISSUE THREAD

**Issue by hirenshah** [DP-Hridayan/aShellYou#12]
Currently running v3.4.0 and have noticed that the Settings aren't saved if you view the Change Log. 

Video attached 🙂

https://github.com/DP-Hridayan/aShellYou/assets/418112/bf4c21d8-c764-43d3-9bc8-4953c6bf4b5f

**Comment by DP-Hridayan** [comment]
I am aware of this bug and already fixed it . Fix will be available in
v3.4.0 stable.  Thank you for noticing though.
