### ISSUE TITLE
新增Android沉浸模式选项

### ISSUE THREAD

**Issue by LegendEast** [DP-Hridayan/aShellYou#133]
可否在设置中新增一个“沉浸模式”选项来隐藏状态栏和操作条？

**Comment by DP-Hridayan** [comment]
您要说的操作栏是什么？您可以截图给我看看吗？

**Comment by LegendEast** [comment]
The action bar shown at the bottom of the screen
![IMG_20240801_180826](https://github.com/user-attachments/assets/713684f4-3d85-4416-b859-7db40523bc4c)

**Comment by KrishnaSSH** [comment]
> The action bar shown at the bottom of the screen ![IMG_20240801_180826](https://private-user-images.githubusercontent.com/162736892/354181344-713684f4-3d85-4416-b859-7db40523bc4c.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI1MDg5MzAsIm5iZiI6MTcyMjUwODYzMCwicGF0aCI6Ii8xNjI3MzY4OTIvMzU0MTgxMzQ0LTcxMzY4NGY0LTNkODUtNDQxNi1iODU5LTdkYjQwNTIzYmM0Yy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwMVQxMDM3MTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NmUzOWMzZjg5NTUwZjYyNDgxMDEwMWVhZjYyNTQ1MjhlZGJkMDUzYWE2YWMxODQ5OTg3NmYwM2VhYjRlOTBiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.MFr7hviV1LIlZWeE6qtceAtbsKD2GjTIN6N9IcULHt0)

that's fixed in latest test build
