### ISSUE TITLE
rpot

### ISSUE THREAD

**Issue by Axelmj2006** [DP-Hridayan/aShellYou#154]
root

**Comment by DP-Hridayan** [comment]
What do you mean?

**Comment by KrishnaSSH** [comment]
Lol 😆

**Comment by KrishnaSSH** [comment]
Root functionality is already done

**Comment by DP-Hridayan** [comment]
Root is currently being tested and will be available in the next update !

**Comment by Axelmj2006** [comment]
> Root is currently being tested and will be available in the next update !
