### ISSUE TITLE
[Suggestion] Add Amoled Theme and Add it on F-Droid Repo

### ISSUE THREAD

**Issue by SagXD** [DP-Hridayan/aShellYou#2]
I have Amoled display. So, adding a Pure Black Theme can reduce battery usage. And  
for adding this to F-Droid I think you need to Rename this App because original aShell app is on F-Droid Repo. Here's Just a some name suggestion like aShell You, ADB You or Material  Shell. I suck at naming choose a name  yourself . 
Here's some guide to add app to F-Droid: [Guide](https://f-droid.org/en/docs/Submitting_to_F-Droid_Quick_Start_Guide/), [Inclusion Policy](https://f-droid.org/en/docs/Inclusion_Policy/) and [Detailed Guide](https://f-droid.org/en/docs/Inclusion_How-To/)

Thank You

**Comment by DP-Hridayan** [comment]
Done . Added amoled theme and also published in fdroid repo.

**Comment by shuvashish76** [comment]
>  also published in fdroid repo.

I don't see it in official F-Droid repo. It's only available on [IzzyOnDroid](https://apt.izzysoft.de/fdroid/index/apk/in.hridayan.ashell) repository.
The original request was about inclusion in official F-Droid repo.

**Comment by shuvashish76** [comment]
> I will try to add a Check for update functionality in the app after I complete the
Settings .

I see the update checker is enabled by default, connects to` raw.githubusercontent.com`.
Please make it opt-in i.e. disabled by default, unless it requires [**Tracking** Anti-Feature](https://f-droid.org/en/docs/Anti-Features/#Tracking) for IzzyOnDroid/F-Droid as update checker is enabled by default.

**Comment by DP-Hridayan** [comment]
Thanks for pointing it out , I will disable it by default.
And yes it got included in izzy on droid rather than fdroid. I have got no reply to my fdroid issue.

**Comment by shuvashish76** [comment]
> I have got no reply to my fdroid issue.

Sorry to hear that. I see your F-Droid [rfp](https://gitlab.com/fdroid/rfp/-/issues/2692) pending for a while.
Perhaps F-Droid maintainers are busy with other things...someone needs to create a merge request, maybe try it yourself : see https://gitlab.com/fdroid/fdroiddata/blob/master/CONTRIBUTING.md#merge-requests

**Comment by RokeJulianLockhart** [comment]
> https://github.com/DP-Hridayan/aShellYou/issues/2#issuecomment-2258445614

These F-Droid request issue should be split from the OLED theme one.
