### ISSUE TITLE
singing config

### ISSUE THREAD

**Issue by IzzySoft** [DP-Hridayan/aShellYou#20]
Did you really [intend this](https://github.com/DP-Hridayan/aShellYou/blob/master/app/build.gradle#L32)? At least the keystore itself isn't here (yet) as well, but I'd say this line shouldn't be here either :wink: You might wish to update and change the pass…

**Comment by DP-Hridayan** [comment]
Thanks for replying. Sorry for the inconvenience I have caused because I am
still very new to app development. I have modified the key password and
have it defined in a properties file which I have included in git ignore.
Now can you tell me how exactly can I submit or make you access the
keystore file and pass so that you can sign the application!

**Comment by DP-Hridayan** [comment]
Thanks for the reply . I understood the signing thing properly now thanks
to your explanation. About the read / write storage permission , it is
required to save the adb output into a txt file . As my app offers features
like logcat , it is required to save the log output as txt file.

**Comment by IzzySoft** [comment]
Thanks! Permission description added. Looking forward to the blob disappearing then :smiley:

**Comment by DP-Hridayan** [comment]
Ok , I will make it , actually I almost forgot that the app is on izzy on
droid rather than fdroid.

**Comment by DP-Hridayan** [comment]
So I have a query about screenshots of the app shown in izzy repo . When I
replaced old screenshots with new ones the old ones also remained along
with new ones in app showcase . Is there some fix or something I might be
missing?

**Comment by KrishnaSSH** [comment]
i made the new badges

**Comment by DP-Hridayan** [comment]
nice

**Comment by IzzySoft** [comment]
> When I replaced old screenshots with new ones the old ones also remained along with new ones in app showcase

I assume you changed the file extension (like from `.png` or `.jpg` to `.jpeg`) while keeping the same naming? As that's the only known case where such things happen. (looking it up) Bingo: I see `.jpg` ***and*** `.jpeg` with the same names. OK, I've removed the old `.jpg` files manually now, should be reflected with the next sync in less than an hour.

> i made the new badges

Oh, speaking of badges: maybe you want to [pick a badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) to link to your app at IoD from e.g. your Readme as well? Or a shield.io shield?

**Comment by DP-Hridayan** [comment]
Oh so that's the issue . Thanks for the fix! I will keep that in mind.

**Comment by IzzySoft** [comment]
At least it's easily fixed once I get to know. And luckily happens rarely (this is just the 2nd or 3rd time at all IIRC).
