### ISSUE TITLE
Play Protect

### ISSUE THREAD

**Issue by Berandal2022** [DP-Hridayan/aShellYou#3]
ashell version 2.0.2 is blocked, I can't update

**Comment by DP-Hridayan** [comment]
Does Play protect blocks installation? If so then you will have to force
install by "install anyway" option.

**Comment by hirenshah** [comment]
Play Protect seems to flag this as unsafe. Doesn't do that with aShell or any other apps that use Shizuku, bypass low target block etc.

**Comment by DP-Hridayan** [comment]
This issue is most probably because aShellYou  isn't released in Play Store
yet . I will look into fixing the unsafe flag without having to list my app
in Play Store because I don't plan to list it on Play Store as of now.

**Comment by hirenshah** [comment]
I don't think that's the reason because many of the apps I have are not available in the Play Store.

Interestingly, the latest version isn't being flagged any more. It doesn't even warn me during install (I had to select "install anyway" for the previous version).

**Comment by DP-Hridayan** [comment]
That's great news. Still I will look into possible issues in my code if
there exists any. Thanks for your feedback

**Comment by Berandal2022** [comment]
I have gone through it, when I wanted to update version 2.0.2 I was warned by Play Protect that the application was dangerous, then I went to Play Protect Play Store. I was advised to uninstall Ashell, but after I scanned Play Protect the warning disappeared and returned to normal

**Comment by DP-Hridayan** [comment]
Yes that is indeed the case . After the scan app turns out to be safe .
