### ISSUE TITLE
Contribution 

### ISSUE THREAD

**Issue by Krishna-G-OP** [DP-Hridayan/aShellYou#4]
@DP-Hridayan,

I am a web developer, I'd be happy to contribute to your project and its continued development. I've reviewed the project and believe my skills in web development could be valuable. I see that there is no current active website of this project so I think i can contribute to the process of web development as I'm interested in exploring contribution opportunities.
Please let me know how I can best get involved based on the project's current needs.

**Comment by DP-Hridayan** [comment]
Hey ,
Thanks for your interest in contributing to the project . But I am a
student and as aShell You is also a free project , therefore I currently
have no way of paying you for your work. However you can create the website
for the app if you want ! And if the website generates any revenue it will
be yours .

**Comment by Krishna-G-OP** [comment]
@DP-Hridayan 

"I do not seek any monetary compensation for the creation of the project's website. My motivation stems from a desire to contribute to open-source initiatives and support the community. Creating the website is a voluntary endeavor aimed at fostering collaboration and advancing the project's objectives."

**Comment by DP-Hridayan** [comment]
Thanks . I am really grateful for your willingness to contribute
voluntarily to the project's website. I will be happy to work together and
see how our skills and passion enhance the project.

**Comment by Krishna-G-OP** [comment]
I would be delighted to collaborate with you as well. Please feel free to reach out to me via email.

**Comment by DP-Hridayan** [comment]
> I would be delighted to collaborate with you as well. Please feel free to reach out to me via email, in case if you don't know it's in my profile.

Sure.

**Comment by Krishna-G-OP** [comment]
@DP-Hridayan hii

**Comment by DP-Hridayan** [comment]
> @DP-Hridayan hii

hello can you join my telegram for discussion https://t.me/aShellYou

**Comment by Krishna-G-OP** [comment]
I joined it but i don't have perms to chat

**Comment by DP-Hridayan** [comment]
> I joined it but i don't have perms to chat

I see
