### ISSUE TITLE
Publish on Accrescent store

### ISSUE THREAD

**Issue by shuvashish76** [DP-Hridayan/aShellYou#55]
Would you please consider publishing it on [Accrescent](https://github.com/accrescent/accrescent); an alternative android app store?

See their guide: https://accrescent.app/docs/guide/getting-started/

**Comment by DP-Hridayan** [comment]
Ok I will see how to publish there !

**Comment by shuvashish76** [comment]
The project is still in alpha phase, you can contact them on [Matrix](https://matrix.to/#/#accrescent:matrix.org), if you've any queries.

**Comment by DP-Hridayan** [comment]
Ok I will

**Comment by Krishna-G-OP** [comment]
> Ok I will

Have you ever used matrix 👀

**Comment by shuvashish76** [comment]
Or better use their GH issue tracker since it's foss :)

**Comment by Krishna-G-OP** [comment]
> Or better use their GH issue tracker since it's foss :)

Who cares what's FOSS what's not 💀
