### ISSUE TITLE
OTG模式空指针

### ISSUE THREAD

**Issue by LegendEast** [DP-Hridayan/aShellYou#64]
连接OTG设备后选择OTG模式会因为空指针闪退崩溃。

After connecting the OTG device and selecting the OTG mode, it will crash due to the null pointer.

Android13,MIUI14.0.10

**Comment by DP-Hridayan** [comment]
Yes I am aware of that crash issue , fix will be coming soon ! Till then
use shizuku + local ADB to run commands.
