### ISSUE TITLE
add cd command to example commands 

### ISSUE THREAD

**Issue by realeatham** [DP-Hridayan/aShellYou#73]
It changes the working directory same as on windows 

If there is a easy way to add commands to it please tell me so if I want another one added I can make a pr instead of an issue

**Comment by Krishna-G-OP** [comment]
@DP-Hridayan wake up 💀💀

**Comment by realeatham** [comment]
@Krishna-G-OP don't be a dick

**Comment by Krishna-G-OP** [comment]
> @Krishna-G-OP don't be a dick

Bruh what's ur problem

**Comment by DP-Hridayan** [comment]
![Screenshot_20240426-134239.png](https://github.com/DP-Hridayan/aShellYou/assets/157479796/8f0dea9f-3a50-4f4c-bb86-3c57b9a5b937)

cd commands added

**Comment by realeatham** [comment]
Thanks
